language: java
sudo: false
jdk:
  - openjdk7
  - openjdk8

script: mvn clean install

deploy:
  provider: script
  script: mvn deploy --settings travis-maven-settings.xml -DskipTests
  on:
    branch: master
    jdk: openjdk7
