language: java
sudo: false
jdk:
  - openjdk7
branches:
  except:
    - travis
script: mvn clean install
deploy:
  if: branch = master
    script: "mvn deploy --settings travis-maven-settings.xml -DskipTests"

